version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "7000:6379" # Map Redis default port
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data # Persist data on the host

volumes:
  redis_data:
    driver: local
