services:
  - type: web
    name: zafon
    runtime: node  # Specify the Node.js version
    buildCommand: |
      yarn install
    startCommand: yarn run start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
